### ISSUE TITLE
Argument numbers mismatch for self.backend.get_all_callers(

### ISSUE THREAD

**Issue by lamwassi** [IBM/codellm-devkit#28]
https://github.com/IBM/codellm-devkit/blob/main/cldk/analysis/java/java.py#L172

returning  `self.backend.get_all_callers(target_class_name,target_method_declaration, using_symbol_table)`  instead of 
                  ` self.backend.get_all_callers(target_class_name, target_method_declaration)`

https://github.com/IBM/codellm-devkit/blob/main/cldk/analysis/java/codeanalyzer/codeanalyzer.py#L444

# Error

TypeError: JCodeanalyzer.get_all_callers() takes 3 positional arguments but 4 were given

**Comment by rangeetpan** [comment]
Fixed
